# Generated by Django 4.1.3 on 2022-11-26 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinantion_name', models.CharField(max_length=400)),
                ('image', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=400)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('package_desc', models.CharField(max_length=1000)),
                ('image', models.FileField(default='', upload_to='')),
                ('duration', models.IntegerField(default=2)),
                ('population', models.IntegerField(default=2)),
                ('destination', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=400)),
                ('category_description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=400)),
                ('optional', models.BooleanField()),
                ('price', models.FloatField(default=0.0)),
                ('desc', models.CharField(default='', max_length=4000)),
                ('location', models.CharField(default='', max_length=200)),
                ('image', models.FileField(default='', upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.servicecategory')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItemGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='', upload_to='')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.serviceitem')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceChargeCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charger', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.servicecategory')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.service')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.serviceitem')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('adults', models.IntegerField()),
                ('kids', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('isPaid', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.serviceitem')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.servicecategory'),
        ),
        migrations.CreateModel(
            name='PackageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=255)),
                ('is_optional', models.BooleanField(default=True)),
                ('price', models.FloatField(default=0.0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('package', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.package')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('adults', models.IntegerField()),
                ('kids', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=200)),
                ('amount', models.FloatField()),
                ('isPaid', models.BooleanField(default=False)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.package')),
            ],
        ),
    ]
