# Generated by Django 4.1.3 on 2022-12-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JVSafarisMain', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honeymoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.destination')),
            ],
        ),
    ]
