# Generated by Django 4.1.3 on 2022-12-07 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JVSafarisMain', '0003_honeymoon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=4200)),
                ('message', models.CharField(max_length=4200)),
                ('date', models.DateField(default=datetime.datetime(2022, 12, 7, 14, 37, 3, 150022))),
            ],
        ),
    ]
