# Generated by Django 4.1.3 on 2022-12-10 02:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JVSafarisMain', '0006_testimonial_alter_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1200)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 12, 10, 2, 2, 0, 327553)),
        ),
        migrations.AddField(
            model_name='package',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.packagecategory'),
            preserve_default=False,
        ),
    ]
