# Generated by Django 4.1.3 on 2022-12-11 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JVSafarisMain', '0009_alter_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='duration',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='kids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
