# Generated by Django 4.1.3 on 2022-12-13 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JVSafarisMain', '0010_serviceitem_adults_serviceitem_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('charge', models.FloatField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JVSafarisMain.package')),
            ],
        ),
    ]
